// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Reflection.Emit;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace APICatalogo.Models
{
  public partial class CatalogoDbEfPowerContext : IdentityDbContext<ApplicationUser>
  {
    public CatalogoDbEfPowerContext(DbContextOptions<CatalogoDbEfPowerContext> options)
        : base(options)
    {
    }

   
    public virtual DbSet<Categoria> Categorias { get; set; }
    public virtual DbSet<Produto> Produtos { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.Entity<Categoria>(entity =>
      {
        entity.Property(e => e.ImagemUrl)
            .IsRequired()
            .HasMaxLength(301)
            .HasDefaultValue("");
        entity.Property(e => e.Nome)
            .IsRequired()
            .HasMaxLength(80)
            .HasDefaultValue("");
      });

      modelBuilder.Entity<Produto>(entity =>
      {
        entity.Property(e => e.Descricao)
            .IsRequired()
            .HasMaxLength(300)
            .HasDefaultValue("");
        entity.Property(e => e.ImagemUrl)
            .IsRequired()
            .HasMaxLength(300)
            .HasDefaultValue("");
        entity.Property(e => e.Nome)
            .IsRequired()
            .HasMaxLength(80)
            .HasDefaultValue("");
        entity.Property(e => e.Preco).HasColumnType("decimal(10, 2)");

        entity.HasOne(d => d.Categoria).WithMany(p => p.Produtos).HasForeignKey(d => d.CategoriaId);
      });

      base.OnModelCreating(modelBuilder);
    }

  }
}
