// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APICatalogo.Models;

public partial class Produto
{
    public int ProdutoId { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public decimal Preco { get; set; }

    public string ImagemUrl { get; set; }

    public float Estoque { get; set; }

    public DateTime DataCadastro { get; set; }

    public int CategoriaId { get; set; }

    public virtual Categoria Categoria { get; set; }
}